export const STORY_LINES = [
  {
    file: '01_narrator_evening.wav',
    speaker: { en: 'Narrator', zh: '旁白', id: 'Narator' },
    text: {
      en: "One cold evening in Aksehir, a hungry traveler stopped beside a cook's cauldron.",
      zh: '一个寒冷的夜晚，在阿克谢希尔，一位饥肠辘辘的旅人停在了厨师的汤锅旁。',
      id: 'Pada suatu malam yang dingin di Aksehir, seorang musafir lapar berhenti di dekat kuali milik seorang juru masak.',
    },
    chapter: ['I', { en: 'The hungry traveler', zh: '饥饿的旅人', id: 'Musafir yang kelaparan' }],
  },
  {
    file: '02_narrator_bread.wav',
    speaker: { en: 'Narrator', zh: '旁白', id: 'Narator' },
    text: {
      en: 'He had only a piece of dry bread. So he held it over the fragrant steam, then ate it.',
      zh: '他只有一块干面包。于是，他把面包放在香气四溢的热气上烘了烘，然后吃了下去。',
      id: 'Ia hanya punya sepotong roti kering. Maka, dihangatkannya roti itu di atas uap sup yang harum, lalu disantapnya.',
    },
    chapter: ['I', { en: 'The hungry traveler', zh: '饥饿的旅人', id: 'Musafir yang kelaparan' }],
  },
  {
    file: '03_cook_accuses.wav',
    speaker: { en: 'Cook', zh: '厨师', id: 'Juru Masak' },
    text: {
      en: 'Thief! You enjoyed the smell of my soup. You must pay me.',
      zh: '小偷！你闻了我的汤香，就得付钱！',
      id: 'Pencuri! Kau menikmati aroma supku. Kau harus membayarnya!',
    },
    chapter: ['II', { en: 'The price of a scent', zh: '香气的价钱', id: 'Harga sebuah aroma' }],
  },
  {
    file: '04_traveler_answers.wav',
    speaker: { en: 'Traveler', zh: '旅人', id: 'Musafir' },
    text: {
      en: 'But I took nothing. I only warmed my bread in the steam.',
      zh: '可我什么也没拿。我只是用热气暖了暖面包。',
      id: 'Tapi aku tidak mengambil apa pun. Aku hanya menghangatkan roti dengan uapnya.',
    },
    chapter: ['II', { en: 'The price of a scent', zh: '香气的价钱', id: 'Harga sebuah aroma' }],
  },
  {
    file: '05_narrator_hodja.wav',
    speaker: { en: 'Narrator', zh: '旁白', id: 'Narator' },
    text: {
      en: 'Their quarrel drew a crowd, and at its edge stood Nasreddin Hodja.',
      zh: '争吵引来了一群人。人群边上，站着纳斯尔丁·霍加。',
      id: 'Pertengkaran mereka mengundang kerumunan. Di tepinya, berdirilah Nasreddin Hodja.',
    },
    chapter: ['III', { en: 'Hodja arrives', zh: '霍加来了', id: 'Hodja datang' }],
  },
  {
    file: '06_nasreddin_questions.wav',
    speaker: { en: 'Nasreddin', zh: '纳斯尔丁', id: 'Nasreddin' },
    text: {
      en: 'Good cook, you ask payment for the smell of soup?',
      zh: '好厨师，你是在向他索取闻汤香的钱吗？',
      id: 'Juru masak yang baik, kau meminta bayaran untuk aroma sup?',
    },
    chapter: ['III', { en: 'Hodja arrives', zh: '霍加来了', id: 'Hodja datang' }],
  },
  {
    file: '07_cook_insists.wav',
    speaker: { en: 'Cook', zh: '厨师', id: 'Juru Masak' },
    text: {
      en: 'Of course! A pleasure has its price.',
      zh: '当然！享受就该付出代价。',
      id: 'Tentu saja! Setiap kenikmatan ada harganya.',
    },
    chapter: ['III', { en: 'Hodja arrives', zh: '霍加来了', id: 'Hodja datang' }],
  },
  {
    file: '08_nasreddin_purse.wav',
    speaker: { en: 'Nasreddin', zh: '纳斯尔丁', id: 'Nasreddin' },
    text: {
      en: "Then give me the traveler's coin purse.",
      zh: '那么，把这位旅人的钱袋给我。',
      id: 'Kalau begitu, berikan kepadaku kantong uang si musafir.',
    },
    chapter: ['IV', { en: 'A curious payment', zh: '奇特的偿付', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '09_narrator_coins.wav',
    speaker: { en: 'Narrator', zh: '旁白', id: 'Narator' },
    text: {
      en: "Hodja raised the purse beside the cook's ear and shook it. Chink. Chink.",
      zh: '霍加把钱袋举到厨师耳边，轻轻摇了摇。叮当。叮当。',
      id: 'Hodja mengangkat kantong itu ke telinga si juru masak, lalu mengguncangnya. Cring. Cring.',
    },
    chapter: ['IV', { en: 'A curious payment', zh: '奇特的偿付', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '10_cook_demands.wav',
    speaker: { en: 'Cook', zh: '厨师', id: 'Juru Masak' },
    text: {
      en: 'I heard the money. Now hand it over.',
      zh: '我听见钱响了。现在，把钱给我。',
      id: 'Aku sudah mendengar uangnya. Sekarang serahkan kepadaku.',
    },
    chapter: ['IV', { en: 'A curious payment', zh: '奇特的偿付', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '11_nasreddin_judgment.wav',
    speaker: { en: 'Nasreddin', zh: '纳斯尔丁', id: 'Nasreddin' },
    text: {
      en: 'The sound of money is fair payment for the smell of soup.',
      zh: '钱币的响声，正好偿付汤的香气。',
      id: 'Bunyi uang adalah bayaran yang setimpal untuk aroma sup.',
    },
    chapter: ['V', { en: 'The sound of money', zh: '钱币的响声', id: 'Bunyi uang' }],
  },
  {
    file: '12_narrator_ending.wav',
    speaker: { en: 'Narrator', zh: '旁白', id: 'Narator' },
    text: {
      en: 'The crowd laughed. The traveler kept his coins, and the cook was left holding only the echo.',
      zh: '人群笑了。旅人保住了钱币，厨师得到的，只有一缕回声。',
      id: 'Orang-orang pun tertawa. Uang si musafir tetap utuh, sementara sang juru masak hanya kebagian gema.',
    },
    chapter: ['V', { en: 'The sound of money', zh: '钱币的响声', id: 'Bunyi uang' }],
  },
];

export const AUDIO_TRACKS = {
  en: { label: 'English', root: '/audio/stories/smell-of-soup/voice/en/' },
  zh: { label: '中文', root: '/audio/stories/smell-of-soup/voice/zh/' },
  id: { label: 'Bahasa Indonesia', root: '/audio/stories/smell-of-soup/voice/id/' },
};

export const MUSIC_CUES = {
  opening: '/audio/stories/smell-of-soup/music/opening-theme.mp3',
  ambience: '/audio/stories/smell-of-soup/music/market-ambience.mp3',
  ending: '/audio/stories/smell-of-soup/music/ending-theme.mp3',
};

export const UI_COPY = {
  en: {
    htmlLanguage: 'en',
    documentTitle: 'The Smell of Soup & The Sound of Money',
    eyebrow: 'An animated Nasreddin Hodja tale',
    titleHtml: '<span>The smell</span><span class="opening__join">of soup <i>&amp;</i> the sound</span><span>of money</span>',
    deck: 'A poor traveler, an expensive aroma, and the only judgment that could balance them.',
    preparing: 'Preparing the story',
    loading: 'Loading voices & score',
    begin: 'Begin the story',
    ready: 'Voices, music & subtitles on',
    headphones: 'Headphones recommended',
    taleMark: 'A Nasreddin tale',
    chapter: 'Chapter',
    judgment: 'The judgment',
    endingHtml: 'A scent for a sound.<br>A debt paid in full.',
    replay: 'Tell it again',
    pause: 'Pause story',
    resume: 'Resume story',
    mute: 'Mute sound',
    unmute: 'Unmute sound',
    muteMusic: 'Mute music',
    unmuteMusic: 'Unmute music',
    musicMuted: 'Music muted.',
    musicPlaying: 'Music playing.',
    hideSubtitles: 'Hide subtitles',
    showSubtitles: 'Show subtitles',
    started: 'The story has begun.',
    paused: 'Story paused.',
    resumed: 'Story resumed.',
    ended: 'The story has ended.',
    loadError: 'The voices could not be loaded',
    retry: 'Refresh to try again',
    optionsLabel: 'Language and subtitles',
    optionsEyebrow: 'Listening options',
    optionsTitle: 'Hear it your way',
    optionsIntro: 'Choose the performed language and the words shown on screen.',
    voice: 'Voice',
    voiceHelp: 'Fully acted narration',
    subtitles: 'Subtitles',
    subtitlesHelp: 'Choose independently from the voice',
    english: 'English',
    chinese: '中文',
    indonesian: 'Bahasa Indonesia',
    off: 'Off',
    close: 'Close language options',
    allStories: 'All stories',
  },
  id: {
    htmlLanguage: 'id',
    documentTitle: 'Aroma Sup & Gemerincing Uang',
    eyebrow: 'Kisah Nasreddin Hodja dalam animasi',
    titleHtml: '<span>Aroma sup</span><span class="opening__join"><i>&amp;</i> gemerincing</span><span>uang</span>',
    deck: 'Seorang musafir miskin, aroma yang mahal, dan satu-satunya putusan yang mampu menyeimbangkan keduanya.',
    preparing: 'Menyiapkan kisah',
    loading: 'Memuat suara & musik',
    begin: 'Mulai kisahnya',
    ready: 'Suara, musik & subtitle aktif',
    headphones: 'Disarankan memakai headphone',
    taleMark: 'Sebuah kisah Nasreddin',
    chapter: 'Bab',
    judgment: 'Putusannya',
    endingHtml: 'Aroma dibayar bunyi.<br>Lunas sudah utangnya.',
    replay: 'Ceritakan lagi',
    pause: 'Jeda kisah',
    resume: 'Lanjutkan kisah',
    mute: 'Bisukan suara',
    unmute: 'Nyalakan suara',
    muteMusic: 'Bisukan musik',
    unmuteMusic: 'Nyalakan musik',
    musicMuted: 'Musik dibisukan.',
    musicPlaying: 'Musik dinyalakan.',
    hideSubtitles: 'Sembunyikan subtitle',
    showSubtitles: 'Tampilkan subtitle',
    started: 'Kisah dimulai.',
    paused: 'Kisah dijeda.',
    resumed: 'Kisah dilanjutkan.',
    ended: 'Kisah telah usai.',
    loadError: 'Suara tidak dapat dimuat',
    retry: 'Muat ulang halaman untuk mencoba lagi',
    optionsLabel: 'Bahasa dan subtitle',
    optionsEyebrow: 'Pilihan mendengarkan',
    optionsTitle: 'Nikmati dengan caramu',
    optionsIntro: 'Pilih bahasa para pemeran dan tulisan yang tampil di layar.',
    voice: 'Suara',
    voiceHelp: 'Narasi dengan pemeran lengkap',
    subtitles: 'Subtitle',
    subtitlesHelp: 'Boleh berbeda dari bahasa suara',
    english: 'English',
    chinese: '中文',
    indonesian: 'Bahasa Indonesia',
    off: 'Tanpa subtitle',
    close: 'Tutup pilihan bahasa',
    allStories: 'Semua cerita',
  },
  zh: {
    htmlLanguage: 'zh-CN',
    documentTitle: '汤香与钱响 | Wisdom Short Stories',
    eyebrow: '纳斯尔丁·霍加寓言 · 电影化短篇',
    titleHtml: '<span>汤的香气</span><span class="opening__join"><i>与</i> 钱币的响声</span>',
    deck: '一位饥饿的旅人，一缕昂贵的香气，以及一场恰到好处的裁决。',
    preparing: '正在准备故事',
    loading: '加载配音与音乐',
    begin: '开始故事',
    ready: '配音、音乐与字幕已就绪',
    headphones: '建议佩戴耳机',
    taleMark: '纳斯尔丁寓言',
    chapter: '章',
    judgment: '判词',
    endingHtml: '香气用响声偿付。<br>这笔账，两清了。',
    replay: '再听一遍',
    pause: '暂停故事',
    resume: '继续故事',
    mute: '关闭声音',
    unmute: '开启声音',
    muteMusic: '关闭音乐',
    unmuteMusic: '开启音乐',
    musicMuted: '音乐已关闭。',
    musicPlaying: '音乐已开启。',
    hideSubtitles: '隐藏字幕',
    showSubtitles: '显示字幕',
    started: '故事开始了。',
    paused: '故事已暂停。',
    resumed: '故事继续。',
    ended: '故事结束了。',
    loadError: '音频加载失败',
    retry: '请刷新页面重试',
    optionsLabel: '语言与字幕',
    optionsEyebrow: '播放选项',
    optionsTitle: '选择你的听法',
    optionsIntro: '配音与屏幕字幕可以分别选择。',
    voice: '配音',
    voiceHelp: '完整角色演绎',
    subtitles: '字幕',
    subtitlesHelp: '可与配音语言不同',
    english: 'English',
    chinese: '中文',
    indonesian: 'Bahasa Indonesia',
    off: '关闭',
    close: '关闭语言选项',
    allStories: '全部故事',
  },
};

export const CAMERA_POSES = [
  { position: [8.8, 4.5, 10.8], target: [-0.4, 1.3, -1.7], fov: 42 },
  { position: [4.4, 2.7, 6.3], target: [-0.5, 1.35, 0.15], fov: 38 },
  { position: [-3.9, 2.45, 5.2], target: [-1.1, 1.45, 0.15], fov: 35 },
  { position: [3.7, 2.2, 4.6], target: [0.15, 1.35, 0.35], fov: 34 },
  { position: [7.3, 3.2, 6.8], target: [1.05, 1.35, 0.15], fov: 39 },
  { position: [3.5, 2.35, 4.3], target: [1.25, 1.45, 0.05], fov: 32 },
  { position: [-3.4, 2.05, 4.1], target: [-1.15, 1.45, 0.1], fov: 31 },
  { position: [4.3, 3.0, 4.9], target: [0.65, 1.55, 0.15], fov: 34 },
  { position: [-0.2, 3.0, 3.5], target: [0.4, 1.75, 0.1], fov: 27 },
  { position: [-3.0, 2.15, 3.8], target: [-1.0, 1.45, 0.15], fov: 30 },
  { position: [3.0, 2.1, 3.9], target: [0.9, 1.5, 0.05], fov: 29 },
  { position: [7.8, 4.2, 9.2], target: [-0.1, 1.35, -0.3], fov: 42 },
];
