export const STORY_LINES = [
  {
    file: '01_narrator_evening.wav',
    speaker: { en: 'Narrator', id: 'Narator' },
    text: {
      en: "One cold evening in Aksehir, a hungry traveler stopped beside a cook's cauldron.",
      id: 'Pada suatu malam yang dingin di Aksehir, seorang musafir lapar berhenti di dekat kuali milik seorang juru masak.',
    },
    chapter: ['I', { en: 'The hungry traveler', id: 'Musafir yang kelaparan' }],
  },
  {
    file: '02_narrator_bread.wav',
    speaker: { en: 'Narrator', id: 'Narator' },
    text: {
      en: 'He had only a piece of dry bread. So he held it over the fragrant steam, then ate it.',
      id: 'Ia hanya punya sepotong roti kering. Maka, dihangatkannya roti itu di atas uap sup yang harum, lalu disantapnya.',
    },
    chapter: ['I', { en: 'The hungry traveler', id: 'Musafir yang kelaparan' }],
  },
  {
    file: '03_cook_accuses.wav',
    speaker: { en: 'Cook', id: 'Juru Masak' },
    text: {
      en: 'Thief! You enjoyed the smell of my soup. You must pay me.',
      id: 'Pencuri! Kau menikmati aroma supku. Kau harus membayarnya!',
    },
    chapter: ['II', { en: 'The price of a scent', id: 'Harga sebuah aroma' }],
  },
  {
    file: '04_traveler_answers.wav',
    speaker: { en: 'Traveler', id: 'Musafir' },
    text: {
      en: 'But I took nothing. I only warmed my bread in the steam.',
      id: 'Tapi aku tidak mengambil apa pun. Aku hanya menghangatkan roti dengan uapnya.',
    },
    chapter: ['II', { en: 'The price of a scent', id: 'Harga sebuah aroma' }],
  },
  {
    file: '05_narrator_hodja.wav',
    speaker: { en: 'Narrator', id: 'Narator' },
    text: {
      en: 'Their quarrel drew a crowd, and at its edge stood Nasreddin Hodja.',
      id: 'Pertengkaran mereka mengundang kerumunan. Di tepinya, berdirilah Nasreddin Hodja.',
    },
    chapter: ['III', { en: 'Hodja arrives', id: 'Hodja datang' }],
  },
  {
    file: '06_nasreddin_questions.wav',
    speaker: { en: 'Nasreddin', id: 'Nasreddin' },
    text: {
      en: 'Good cook, you ask payment for the smell of soup?',
      id: 'Juru masak yang baik, kau meminta bayaran untuk aroma sup?',
    },
    chapter: ['III', { en: 'Hodja arrives', id: 'Hodja datang' }],
  },
  {
    file: '07_cook_insists.wav',
    speaker: { en: 'Cook', id: 'Juru Masak' },
    text: {
      en: 'Of course! A pleasure has its price.',
      id: 'Tentu saja! Setiap kenikmatan ada harganya.',
    },
    chapter: ['III', { en: 'Hodja arrives', id: 'Hodja datang' }],
  },
  {
    file: '08_nasreddin_purse.wav',
    speaker: { en: 'Nasreddin', id: 'Nasreddin' },
    text: {
      en: "Then give me the traveler's coin purse.",
      id: 'Kalau begitu, berikan kepadaku kantong uang si musafir.',
    },
    chapter: ['IV', { en: 'A curious payment', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '09_narrator_coins.wav',
    speaker: { en: 'Narrator', id: 'Narator' },
    text: {
      en: "Hodja raised the purse beside the cook's ear and shook it. Chink. Chink.",
      id: 'Hodja mengangkat kantong itu ke telinga si juru masak, lalu mengguncangnya. Cring. Cring.',
    },
    chapter: ['IV', { en: 'A curious payment', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '10_cook_demands.wav',
    speaker: { en: 'Cook', id: 'Juru Masak' },
    text: {
      en: 'I heard the money. Now hand it over.',
      id: 'Aku sudah mendengar uangnya. Sekarang serahkan kepadaku.',
    },
    chapter: ['IV', { en: 'A curious payment', id: 'Bayaran yang ganjil' }],
  },
  {
    file: '11_nasreddin_judgment.wav',
    speaker: { en: 'Nasreddin', id: 'Nasreddin' },
    text: {
      en: 'The sound of money is fair payment for the smell of soup.',
      id: 'Bunyi uang adalah bayaran yang setimpal untuk aroma sup.',
    },
    chapter: ['V', { en: 'The sound of money', id: 'Bunyi uang' }],
  },
  {
    file: '12_narrator_ending.wav',
    speaker: { en: 'Narrator', id: 'Narator' },
    text: {
      en: 'The crowd laughed. The traveler kept his coins, and the cook was left holding only the echo.',
      id: 'Orang-orang pun tertawa. Uang si musafir tetap utuh, sementara sang juru masak hanya kebagian gema.',
    },
    chapter: ['V', { en: 'The sound of money', id: 'Bunyi uang' }],
  },
];

export const AUDIO_TRACKS = {
  en: { label: 'English', root: '/audio/story/' },
  id: { label: 'Bahasa Indonesia', root: '/audio/story/id/' },
};

export const MUSIC_CUES = {
  opening: '/audio/music/opening-theme.mp3',
  ambience: '/audio/music/market-ambience.mp3',
  ending: '/audio/music/ending-theme.mp3',
};

export const UI_COPY = {
  en: {
    htmlLanguage: 'en',
    documentTitle: 'The Smell of Soup & The Sound of Money',
    eyebrow: 'An animated Nasreddin Hodja tale',
    titleHtml: '<span>The smell</span><span class="opening__join">of soup <i>&amp;</i> the sound</span><span>of money</span>',
    deck: 'A poor traveler, an expensive aroma, and the only judgment that could balance them.',
    preparing: 'Preparing the story',
    loading: 'Loading voices & score',
    begin: 'Begin the story',
    ready: 'Voices, music & subtitles on',
    headphones: 'Headphones recommended',
    taleMark: 'A Nasreddin tale',
    chapter: 'Chapter',
    judgment: 'The judgment',
    endingHtml: 'A scent for a sound.<br>A debt paid in full.',
    replay: 'Tell it again',
    pause: 'Pause story',
    resume: 'Resume story',
    mute: 'Mute sound',
    unmute: 'Unmute sound',
    muteMusic: 'Mute music',
    unmuteMusic: 'Unmute music',
    musicMuted: 'Music muted.',
    musicPlaying: 'Music playing.',
    hideSubtitles: 'Hide subtitles',
    showSubtitles: 'Show subtitles',
    started: 'The story has begun.',
    paused: 'Story paused.',
    resumed: 'Story resumed.',
    ended: 'The story has ended.',
    loadError: 'The voices could not be loaded',
    retry: 'Refresh to try again',
    optionsLabel: 'Language and subtitles',
    optionsEyebrow: 'Listening options',
    optionsTitle: 'Hear it your way',
    optionsIntro: 'Choose the performed language and the words shown on screen.',
    voice: 'Voice',
    voiceHelp: 'Fully acted narration',
    subtitles: 'Subtitles',
    subtitlesHelp: 'Choose independently from the voice',
    english: 'English',
    indonesian: 'Bahasa Indonesia',
    off: 'Off',
    close: 'Close language options',
  },
  id: {
    htmlLanguage: 'id',
    documentTitle: 'Aroma Sup & Gemerincing Uang',
    eyebrow: 'Kisah Nasreddin Hodja dalam animasi',
    titleHtml: '<span>Aroma sup</span><span class="opening__join"><i>&amp;</i> gemerincing</span><span>uang</span>',
    deck: 'Seorang musafir miskin, aroma yang mahal, dan satu-satunya putusan yang mampu menyeimbangkan keduanya.',
    preparing: 'Menyiapkan kisah',
    loading: 'Memuat suara & musik',
    begin: 'Mulai kisahnya',
    ready: 'Suara, musik & subtitle aktif',
    headphones: 'Disarankan memakai headphone',
    taleMark: 'Sebuah kisah Nasreddin',
    chapter: 'Bab',
    judgment: 'Putusannya',
    endingHtml: 'Aroma dibayar bunyi.<br>Lunas sudah utangnya.',
    replay: 'Ceritakan lagi',
    pause: 'Jeda kisah',
    resume: 'Lanjutkan kisah',
    mute: 'Bisukan suara',
    unmute: 'Nyalakan suara',
    muteMusic: 'Bisukan musik',
    unmuteMusic: 'Nyalakan musik',
    musicMuted: 'Musik dibisukan.',
    musicPlaying: 'Musik dinyalakan.',
    hideSubtitles: 'Sembunyikan subtitle',
    showSubtitles: 'Tampilkan subtitle',
    started: 'Kisah dimulai.',
    paused: 'Kisah dijeda.',
    resumed: 'Kisah dilanjutkan.',
    ended: 'Kisah telah usai.',
    loadError: 'Suara tidak dapat dimuat',
    retry: 'Muat ulang halaman untuk mencoba lagi',
    optionsLabel: 'Bahasa dan subtitle',
    optionsEyebrow: 'Pilihan mendengarkan',
    optionsTitle: 'Nikmati dengan caramu',
    optionsIntro: 'Pilih bahasa para pemeran dan tulisan yang tampil di layar.',
    voice: 'Suara',
    voiceHelp: 'Narasi dengan pemeran lengkap',
    subtitles: 'Subtitle',
    subtitlesHelp: 'Boleh berbeda dari bahasa suara',
    english: 'English',
    indonesian: 'Bahasa Indonesia',
    off: 'Tanpa subtitle',
    close: 'Tutup pilihan bahasa',
  },
};

export const CAMERA_POSES = [
  { position: [8.8, 4.5, 10.8], target: [-0.4, 1.3, -1.7], fov: 42 },
  { position: [4.4, 2.7, 6.3], target: [-0.5, 1.35, 0.15], fov: 38 },
  { position: [-3.9, 2.45, 5.2], target: [-1.1, 1.45, 0.15], fov: 35 },
  { position: [3.7, 2.2, 4.6], target: [0.15, 1.35, 0.35], fov: 34 },
  { position: [7.3, 3.2, 6.8], target: [1.05, 1.35, 0.15], fov: 39 },
  { position: [3.5, 2.35, 4.3], target: [1.25, 1.45, 0.05], fov: 32 },
  { position: [-3.4, 2.05, 4.1], target: [-1.15, 1.45, 0.1], fov: 31 },
  { position: [4.3, 3.0, 4.9], target: [0.65, 1.55, 0.15], fov: 34 },
  { position: [-0.2, 3.0, 3.5], target: [0.4, 1.75, 0.1], fov: 27 },
  { position: [-3.0, 2.15, 3.8], target: [-1.0, 1.45, 0.15], fov: 30 },
  { position: [3.0, 2.1, 3.9], target: [0.9, 1.5, 0.05], fov: 29 },
  { position: [7.8, 4.2, 9.2], target: [-0.1, 1.35, -0.3], fov: 42 },
];
